//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCS.Web.RCSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RCSService.IRCSService")]
    public interface IRCSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRCSService/Test", ReplyAction="http://tempuri.org/IRCSService/TestResponse")]
        RCS.POCO.Test Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRCSService/Test", ReplyAction="http://tempuri.org/IRCSService/TestResponse")]
        System.Threading.Tasks.Task<RCS.POCO.Test> TestAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRCSServiceChannel : RCS.Web.RCSService.IRCSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RCSServiceClient : System.ServiceModel.ClientBase<RCS.Web.RCSService.IRCSService>, RCS.Web.RCSService.IRCSService {
        
        public RCSServiceClient() {
        }
        
        public RCSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RCSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RCSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RCSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RCS.POCO.Test Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<RCS.POCO.Test> TestAsync() {
            return base.Channel.TestAsync();
        }
    }
}
